[package]
name = "ixmati-projector"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ixmati-core = { path = "../ixmati-core" }
ixmati-cache = { path = "../ixmati-cache" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
rumqttc.workspace = true
uuid.workspace = true
tracing-subscriber.workspace = true
