[supervisord]
nodaemon=true
logfile=/var/log/ixmati/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mosquitto]
command=/usr/sbin/mosquitto -c /etc/mosquitto/conf.d/ixmati.conf
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ixmati-api]
command=/usr/local/bin/ixmati-api %(ENV_SQLITE_PATH)s
environment=MQTT_BROKER="tcp://localhost:1883",API_HOST="0.0.0.0",API_PORT="%(ENV_API_PORT)s",IXMATI_API_KEYS="%(ENV_IXMATI_API_KEYS)s"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ixmati-writer]
command=/usr/local/bin/ixmati-writer
environment=MQTT_BROKER="tcp://localhost:1883",STORE_NAME="%(ENV_STORE_NAME)s",SQLITE_PATH="%(ENV_SQLITE_PATH)s"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ixmati-projector]
command=/usr/local/bin/ixmati-projector
environment=MQTT_BROKER="tcp://localhost:1883"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
