FROM docker.io/library/rust:1.85-slim-bookworm

RUN apt-get update -qq && apt-get install -y -qq libclang-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN cargo build --release
RUN cargo run --release
