[package]
name = "ixmati-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ixmati-core = { path = "../ixmati-core" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
uuid.workspace = true
axum.workspace = true
tonic.workspace = true
prost.workspace = true
rumqttc.workspace = true
rusqlite.workspace = true
