[package]
name = "ixmati-supervisor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ixmati-core = { path = "../ixmati-core" }
ixmati-writer = { path = "../ixmati-writer" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
