apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ixmati

resources:
  - namespace.yaml
  - configmap.yaml
  - mosquitto.yaml
  - api.yaml
  - writer.yaml
  - projector.yaml
  - supervisor.yaml
  - litestream.yaml

commonLabels:
  app.kubernetes.io/part-of: ixmati
  app.kubernetes.io/version: "0.1.0"

images:
  - name: ghcr.io/rafex/ixmati-api
    newTag: "0.1.0"
  - name: ghcr.io/rafex/ixmati-writer
    newTag: "0.1.0"
  - name: ghcr.io/rafex/ixmati-projector
    newTag: "0.1.0"
  - name: ghcr.io/rafex/ixmati-supervisor
    newTag: "0.1.0"
  - name: ghcr.io/rafex/ixmati-reconciler
    newTag: "0.1.0"
  - name: ghcr.io/rafex/ixmati-litestream
    newTag: "0.1.0"
  - name: ghcr.io/rafex/ixmati-mosquitto
    newTag: "0.1.0"
