FROM localhost/ixmati-builder:local AS build
FROM docker.io/library/debian:trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /usr/local/bin/ixmati-cache-server /usr/local/bin/ixmati-cache-server

RUN mkdir -p /var/lib/ixmati/cache /var/run/ixmati \
    && chmod 777 /var/lib/ixmati/cache /var/run/ixmati

USER 1000:1000
VOLUME ["/var/lib/ixmati/cache"]

ENTRYPOINT ["ixmati-cache-server"]
