FROM localhost/ixmati-builder:local AS build
FROM docker.io/library/debian:trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /usr/local/bin/ixmati-cache-server /usr/local/bin/ixmati-cache-server

RUN mkdir -p /var/lib/ixmati/cache /var/run/ixmati \
    && useradd --system --no-create-home --shell /usr/sbin/nologin ixmati \
    && chown -R ixmati:ixmati /var/lib/ixmati /var/run/ixmati

USER ixmati
EXPOSE 0
VOLUME ["/var/lib/ixmati/cache"]

ENTRYPOINT ["ixmati-cache-server"]
